#!/bin/bash

# Copy to .git/hooks in the project root
# E.g. cp pre-push ../.git/hooks/ && chmod +x ../.git/hooks/pre-push

echo "Running ktlint..."
sh scripts/ktlint.sh

RESULT=$?
if [ $RESULT -ne 0 ]; then
 echo "Ktlint error. Run sh scripts/ktlint.sh -F to apply fixes"
 exit 1
fi

echo "Running detekt..."
OUTPUT="/tmp/detekt-$(date +%s)"
./gradlew detekt > $OUTPUT
EXIT_CODE=$?
if [ $EXIT_CODE -ne 0 ]; then
  cat $OUTPUT
  rm $OUTPUT
  echo "***********************************************"
  echo "                 Detekt failed                 "
  echo " Please fix the above issues before committing "
  echo "***********************************************"
  exit $EXIT_CODE
fi
rm $OUTPUT

exit 0
